import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutClient from "@/components/app/layout-client";
import { helvetica } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`bg-white ${helvetica.variable}`}>
      <body className={helvetica.className}>
        <ClerkProvider>
          <LayoutClient>{children}</LayoutClient>
        </ClerkProvider>
      </body>
    </html>
  );
}
