import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import BottomTab from "@/components/app/bottom-tab";
import CollapsedSidebar from "@/components/app/collapsed-sidebar";
import ExpandedSidebar from "@/components/app/expanded-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="bg-white">
      <body>
        <ClerkProvider>
          <BottomTab />
          <div className="hidden md:block xl:hidden">
            <CollapsedSidebar />
          </div>
          <div className="hidden xl:block">
            <ExpandedSidebar />
          </div>
          <main className="pb-[60px] md:pb-0 md:pl-[72px] xl:pl-[336px]">
            {children}
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
