import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutClient from "@/components/app/layout-client";
import { helvetica } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TabLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`bg-zinc-950 ${helvetica.variable}`}>
      <body className={helvetica.className}>
        <ClerkProvider>
          <LayoutClient>{children}</LayoutClient>
        </ClerkProvider>
      </body>
    </html>
  );
}
